services:
  db:
    image: postgres:16
    container_name: msd_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - msd25_postgres_data:/var/lib/postgresql/data

volumes:
  msd25_postgres_data:
